apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mymobi-active-mq
  name: mymobi-active-mq-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mymobi-active-mq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mymobi-active-mq
    spec:
      containers:
      - image: vromero/activemq-artemis
        imagePullPolicy: IfNotPresent
        name: active-mq-web
        ports:
        - containerPort: 8161
          protocol: TCP
        - containerPort: 61616
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

