---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: active-mq
  name: active-mq-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: active-mq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: active-mq
    spec:
      containers:
      - image: vromero/activemq-artemis
        imagePullPolicy: IfNotPresent
        name: active-mq-web
        ports:
        - containerPort: 8161
          protocol: TCP
        - containerPort: 61616
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: active-mq-service
  name: active-mq-service
spec:
  ports:
  - name: active-mq-web-port
    port: 8161
    protocol: TCP
    targetPort: 8161
  - name: active-mq-core-port
    port: 61616
    protocol: TCP
    targetPort: 61616
  selector:
    app: active-mq
  type: NodePort


